------------ CONSULTAS BASICAS -------------------
--- Verificar la cantidad de registros por tabla

SELECT COUNT(*) AS Total_Registros FROM DIM_CATEGORY;
SELECT COUNT(*) AS Total_Registros FROM DIM_PRODUCT;
SELECT COUNT(*) AS Total_Registros FROM DIM_SEGMENT;
SELECT COUNT(*) AS Total_Registros FROM DIM_CALENDAR;
SELECT COUNT(*) AS Total_Registros FROM FACT_SALES;

--- Verificar las primeras filas de cada tabla

SELECT TOP 10 * FROM DIM_CATEGORY;
SELECT TOP 10 * FROM DIM_PRODUCT;
SELECT TOP 10 * FROM DIM_SEGMENT;
SELECT TOP 10 * FROM DIM_CALENDAR;
SELECT TOP 10 * FROM FACT_SALES;

--- Verificar valores nulos en columnas clave

SELECT COUNT(*) AS Nulos_ID_CATEGORY FROM DIM_CATEGORY WHERE ID_CATEGORY IS NULL;
SELECT COUNT(*) AS Nulos_ITEM_CODE FROM FACT_SALES WHERE ITEM_CODE IS NULL;
SELECT COUNT(*) AS Nulos_DATE FROM DIM_CALENDAR WHERE DATE IS NULL;

--- Productos más vendidos por valor total

SELECT TOP 10 
    ITEM_CODE, 
    SUM(TOTAL_VALUE_SALES) AS Ventas_Totales 
FROM FACT_SALES
GROUP BY ITEM_CODE
ORDER BY Ventas_Totales DESC;

--- Ventas promedio por región

SELECT 
    REGION, 
    AVG(TOTAL_VALUE_SALES) AS Promedio_Ventas 
FROM FACT_SALES
GROUP BY REGION
ORDER BY Promedio_Ventas DESC;

--- Análisis de ventas por mes

SELECT 
    DC.MONTH, 
    SUM(FS.TOTAL_VALUE_SALES) AS Ventas_Totales 
FROM FACT_SALES FS
INNER JOIN DIM_CALENDAR DC ON FS.WEEK = DC.WEEK
GROUP BY DC.MONTH
ORDER BY DC.MONTH;

--- Ventas totales por categoría

SELECT 
    DC.CATEGORY, 
    SUM(FS.TOTAL_VALUE_SALES) AS Ventas_Totales
FROM FACT_SALES FS
INNER JOIN DIM_PRODUCT DP ON FS.ITEM_CODE = DP.ITEM
INNER JOIN DIM_CATEGORY DC ON DP.CATEGORY = DC.ID_CATEGORY
GROUP BY DC.CATEGORY
ORDER BY Ventas_Totales DESC;

--- Análisis temporal de ventas por región

SELECT 
    DC.YEAR, 
    DC.MONTH, 
    FS.REGION, 
    SUM(FS.TOTAL_VALUE_SALES) AS Ventas_Totales
FROM FACT_SALES FS
INNER JOIN DIM_CALENDAR DC ON FS.WEEK = DC.WEEK
GROUP BY DC.YEAR, DC.MONTH, FS.REGION
ORDER BY DC.YEAR, DC.MONTH, FS.REGION;